### ISSUE TITLE
certificate for us-east-1

### ISSUE THREAD

**Issue by bknutson123** [byu-oit/terraform-aws-acs-info#16]
We need the certificate from us-east-1 so we can create certain products (API Gateway, CloudFront, maybe others)

**Comment by joshgubler** [comment]
https://www.terraform.io/docs/configuration/resources.html#provider-selecting-a-non-default-provider-configuration

**Comment by joshgubler** [comment]
Terraform recommends not specifying provider details inside child modules. Rather, the root module should pass provider details down into child modules.
https://www.terraform.io/docs/configuration/modules.html#providers-within-modules

In this case, that means we wouldn't implement this request inside the acs-info module. Instead, consumers of the module should create two instances of acs-info, and pass a `us-east-1` alias provider into one of them.

However, needing the cert from us-east-1 is super common. I'm fine violating the recommendation in this case for convenience. That way everybody doesn't have to understand how to pass in an aliased provider. (I think it's more of an edge case. Other than getting the cert, I don't think people will need to be multi region very often.)

I guess I could see it either way. What does everybody else think @byu-oit/terraform-developers ?

Do we prefer convenience, or training?
